export const selectLabels = [
    {
        id: 1,
        label: 'Restaurants',
        image: require('../.././assets/Food.png'),
        width: 140,
        justifyContent: 'flex-end',
        widthImage: 45,
        height: 35,
    },
    {
        id: 2,
        label: 'Grocery',
        image: require('../.././assets/Grocery.png'),
        width: 140,
        justifyContent: 'flex-end',
        widthImage: 45,
        height: 35,
    },
    {
        id: 3,
        labelBottom: 'Convenience',
        image: require('../.././assets/Conv.png'),
        width: 75,
        justifyContent: 'center',
        widthImage: 35,
        height: 25,
    },
    {
        id: 4,
        labelBottom: 'Alcohol',
        image: require('../.././assets/alcohol.png'),
        width: 70,
        justifyContent: 'center',
        widthImage: 35,
        height: 25,
    },
    {
        id: 5,
        labelBottom: 'Ride',
        image: require('../.././assets/uber.png'),
        width: 70,
        justifyContent: 'center',
        widthImage: 35,
        height: 25,
    },
    {
        id: 6,
        labelBottom: 'See all',
        image: require('../.././assets/more.png'),
        width: 65,
        justifyContent: 'center',
        widthImage: 24,
        height: 25,
    },
];
